# an available choice for the specs control
name:
  VulnerabilityPolicy
description:
  detect image vulnerabilities
multiselect:
  specs
replacements: # if user select this choice, the template variable names and values to use
  categories: |
    DetectImageVulnerabilities
  policyTemplates: |
    - objectDefinition:
        apiVersion: policies.ibm.com/v1alpha1
        kind: VulnerabilityPolicy # detect image vulnerabilities
        metadata:
          name: {{name}}-example
          label:
            category: "System-Integrity"
        spec:
          namespaceSelector:
            include: ["default","kube-*"]
            exclude: ["kube-system"]
          remediationAction: inform # enforce or inform
          severity: medium
