sudo: required
language: node_js

matrix:
  fast_finish: true
  include:
    - os: linux-s390
      env: OSARCH=linux-s390
      dist: trusty
    - os: linux-ppc64le
      env: OSARCH=linux-ppc64le
      dist: trusty
    - os: linux
      env: OSARCH=linux-amd64
      dist: trusty

addons:
  packages:
    - openjdk-8-jdk
  chrome: stable

cache:
  apt: true

branches:
  only:
    - master
    - dev
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

services:
  - docker
  - xvfb

before_install:
  - make init

install:
  - npm install
  - chmod +x copyright-check.sh
  - make copyright-check
  - make unit-test

before_script:
  - make local
  - make image
  - make run

script:
  - make e2e-test
  - export PREV_COVERAGE_REPORT=$(curl -L -H 'Authorization:token ${GITHUB_TOKEN}' https://raw.github.ibm.com/IBMPrivateCloud/grc-ui/gh-pages/coverage/coverage-summary.json)
  - node travis-scripts/enforce-coverage.js

after_success:
  - test "$TRAVIS_EVENT_TYPE" = "pull_request" && make push || echo "pushing to scratch"
  - test "$TRAVIS_EVENT_TYPE" != "pull_request" && make release || echo "success"
  - |
      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
        curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
        python travis_after_all.py https://travis.ibm.com/api
        export $(cat .to_export_back)
        if [[ "$BUILD_LEADER" == "YES" ]]; then
          if [[ "$BUILD_AGGREGATE_STATUS" == "others_succeeded" ]]; then
            echo "All jobs succeeded! Creating multi arch image..."
            make docker:manifest-tool
            make docker:multi-arch
          else
            echo "Some jobs failed" && exit 1
          fi
        fi
      fi

after_failure:
  - |
      if [ -d "test-output" ]; then
        sudo apt-get install -y expect
        mkdir selenium-test && mkdir selenium-test/$TRAVIS_JOB_NUMBER && cp -R test-output/e2e selenium-test/$TRAVIS_JOB_NUMBER
        expect upload-selenium.sh
        echo Selenium test failed! Result available at http://9.37.247.85:81/$TRAVIS_JOB_NUMBER/e2e/
      fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: test-output
  github-url: github.ibm.com
  on:
    branch: master
