sudo: required
language: node_js

os:
  - linux-ppc64le
  - linux

addons:
  packages:
    - openjdk-8-jdk
  chrome: stable

cache:
  apt: true
  directories:
    - "$TRAVIS_CACHE_DIR"

before_cache:
  - sudo rm -rf $TRAVIS_CACHE_DIR/selenium-standalone

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

services:
  - docker

before_install:
  - make cicd-log-init
  - source travis-env.sh
  - make docker-login

install:
  - make install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - make image
  - make run
  - chmod +x copyright-check.sh

script:
  - make copyright-check
  - make test
#  - make cicd-log-test
  - export PREV_COVERAGE_REPORT=$(curl -L -H 'Authorization:token ${GITHUB_TOKEN}' https://raw.github.ibm.com/IBMPrivateCloud/mcm-ui/gh-pages/coverage/coverage-summary.json)
  - node travis-scripts/enforce-coverage.js

after_success:
  - make push
  - test "$TRAVIS_EVENT_TYPE" != "pull_request" && make release || echo "success"
  - |
      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
        curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
        python travis_after_all.py https://travis.ibm.com/api
        export $(cat .to_export_back)
        if [[ "$BUILD_LEADER" == "YES" ]]; then
          if [[ "$BUILD_AGGREGATE_STATUS" == "others_succeeded" ]]; then
            echo "All jobs succeeded! Creating multi arch image..."
            make manifest-tool
            make multi-arch
          else
            echo "Some jobs failed" && exit 1
          fi
        fi
      fi
  - make cicd-log-success

after_failure:
  - |
      if [ -d "test-output" ]; then
        sudo apt-get install -y expect
        mkdir selenium-test && mkdir selenium-test/$TRAVIS_JOB_NUMBER && cp -R test-output/e2e selenium-test/$TRAVIS_JOB_NUMBER
        expect upload-selenium.sh
        echo Selenium test failed! Result available at http://9.42.81.137:81/$TRAVIS_JOB_NUMBER/e2e/
      fi
  - make cicd-log-fail

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: test-output
  github-url: github.ibm.com
  on:
    branch: master

notifications:
  slack:
    secure: VYEghDGikEyR83C23NsbJ12A+h4TlFPC7xVn1ezrnGoIPnGVaffwXNQAyzBOMxEOG24fXY3LxpvJSL2dh/bXkMf6v6QgP43YC2csM5CYKsW2clYhXxD2o85rtpS8HFP39CvhhocK2hk4sMn1kdu7CktkejmdGu9t0DIAaIkehyIr7m5Ru8t/iSsyq1ySesOwl22hOJFja2bLDJB+W8IbYXzvkQRSbsVBkkI+9x6DZ7DZFqUM1ugEK0ptufD03LWmSojpbaG75MQdT2U8TLrOQOeUoInQi3CJFZLz8Ca6cVfXm7gX9KBrcyD2ZR5K6eIFeAhzH4sj6TIklUrN+QhVYumWk7hAFpLCjvbYCoemOKEFVPHt6AYmBZ0qa/mNSnfxwO+W5Q0J3yq3Nx0RMO75mDuKJhksTjLh1hLftWRe1tmp7T4C79oyZ0xWlWtLgT8jTZPBFnCDfLBJfI70qkqRKJ83sa6n85lkCeAHOvRgYkyZqsCI8OedRD3tIZnB4Ny24SYibinF1X2HcF7ryseEEPPrpx3v6hQStMAnS2bqHcl4ynxFDwRGcHA3XPOlCquR3BETtMrk3lRusSZp9PTxIh8MNeCyXZRMUFoMY4330PlNYw8v7+MlHJDurqcesW87zUOeO95zB5Rs2sK//kA5QsIJPsBBMqRwcTbPx8dhw+o=
    on_pull_requests: false
    on_success: change
    on_failure: always
