sudo: required
language: node_js

os:
  - linux-ppc64le
  - linux

addons:
  packages:
    - openjdk-8-jdk
  chrome: stable

cache:
  apt: true

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

services:
  - docker
  - xvfb

before_install:
  - source travis-env.sh


install:
  - make install

before_script:
  - make docker-login-edge
  - make image
  - make run
  - chmod +x copyright-check.sh

script:
  - make copyright-check
  - make docker-login
  - make test
  - export PREV_COVERAGE_REPORT=$(curl -L -H 'Authorization:token ${GITHUB_TOKEN}' https://raw.github.ibm.com/IBMPrivateCloud/grc-ui/gh-pages/coverage/coverage-summary.json)
  - node travis-scripts/enforce-coverage.js

after_success:
  - make push
  - test "$TRAVIS_EVENT_TYPE" != "pull_request" && make release || echo "success"
  - |
      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
        curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
        python travis_after_all.py https://travis.ibm.com/api
        export $(cat .to_export_back)
        if [[ "$BUILD_LEADER" == "YES" ]]; then
          if [[ "$BUILD_AGGREGATE_STATUS" == "others_succeeded" ]]; then
            echo "All jobs succeeded! Creating multi arch image..."
            make manifest-tool
            make multi-arch
          else
            echo "Some jobs failed" && exit 1
          fi
        fi
      fi

after_failure:
  - |
      if [ -d "test-output" ]; then
        sudo apt-get install -y expect
        mkdir selenium-test && mkdir selenium-test/$TRAVIS_JOB_NUMBER && cp -R test-output/e2e selenium-test/$TRAVIS_JOB_NUMBER
        expect upload-selenium.sh
        echo Selenium test failed! Result available at http://9.37.247.85:81/$TRAVIS_JOB_NUMBER/e2e/
      fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: test-output
  github-url: github.ibm.com
  on:
    branch: master
